"""
Test script to compare OAuth URLs generated by Python vs expected JavaScript behavior
"""
from urllib.parse import quote
import secrets

def build_auth_url_python(authorize_url, client_id, redirect_uri, scope, state, fhir_base_url, launch=None):
    """Our Python implementation"""
    # Validate launch
    if launch:
        launch = str(launch).strip()
        if not launch or launch == "None":
            launch = None

    # Add "launch" to scope if launch token exists
    if launch and "launch" not in scope:
        scope = scope + " launch"

    # Build parameters
    redirect_params = [
        f"response_type=code",
        f"client_id={quote(client_id, safe='')}",
        f"scope={quote(scope, safe='')}",
        f"redirect_uri={quote(redirect_uri, safe='')}",
        f"aud={quote(fhir_base_url, safe='')}",
        f"state={quote(state, safe='')}"
    ]

    if launch:
        redirect_params.append(f"launch={quote(launch, safe='')}")

    return f"{authorize_url}?{'&'.join(redirect_params)}"


def main():
    # Test parameters (matching Taiwan MOHW)
    authorize_url = "https://thas.mohw.gov.tw/v/r4/sim/WzIslilslilslkFVVE8iLDAsMCwwLCIiLCIiLCIiLCIiLCIiLCIiLCIiLCIiLDAsMSwill0/fhir/oauth/authorize"
    client_id = "demo_client"
    redirect_uri = "https://wftmufhir.streamlit.app/"
    scope = "openid fhirUser patient/Patient.read patient/Observation.read patient/Observation.write patient/Condition.read patient/MedicationRequest.read patient/MedicationAdministration.read"
    state = "test_state_123"
    fhir_base_url = "https://thas.mohw.gov.tw/v/r4/sim/WzIslilslilslkFVVE8iLDAsMCwwLCIiLCIiLCIiLCIiLCIiLCIiLCIiLCIiLDAsMSwill0/fhir"

    print("=" * 80)
    print("TEST 1: Standalone Launch (no launch parameter)")
    print("=" * 80)
    url1 = build_auth_url_python(authorize_url, client_id, redirect_uri, scope, state, fhir_base_url, launch=None)
    print(f"\nGenerated URL:\n{url1}\n")
    print(f"URL Length: {len(url1)}")

    print("\n" + "=" * 80)
    print("TEST 2: EHR Launch (with launch parameter)")
    print("=" * 80)
    launch_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.test.signature"
    url2 = build_auth_url_python(authorize_url, client_id, redirect_uri, scope, state, fhir_base_url, launch=launch_token)
    print(f"\nGenerated URL:\n{url2}\n")
    print(f"URL Length: {len(url2)}")
    print(f"\nLaunch token encoded: {quote(launch_token, safe='')}")

    print("\n" + "=" * 80)
    print("EXPECTED JavaScript behavior:")
    print("=" * 80)
    print("""
JavaScript (fhirclient.js) would build the URL as:
1. Start with authorize endpoint
2. Add parameters in order:
   - response_type=code
   - client_id=<encoded>
   - scope=<encoded> (with " launch" appended if launch token exists)
   - redirect_uri=<encoded>
   - aud=<encoded FHIR base URL>
   - state=<encoded>
   - launch=<encoded> (only if launch token exists)
3. Use encodeURIComponent() for each value
""")


if __name__ == "__main__":
    main()
